/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreUObject.h"
#include "Json/Public/Json.h"
#include "Json/Public/Serialization/JsonWriter.h"
#include "OpenAPIModule.h"
#include "Helpers.h"
#include "User.generated.h"


/*
* User Model related types and methods.
*
* A User who is purchasing from the pet store
*/

// declare any enum types



//Blueprint UObject for User
UCLASS(BlueprintType)
class OPENAPI_API UOAPIUser : public UOAPIModel
{

    GENERATED_BODY()

public:

    bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
    void WriteJson(JsonWriter& Writer) const override;


    TOptional<int64> Id;

    UFUNCTION(BlueprintCallable)
    const int64 GetId() const { return this->Id.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetId(int64 In_Id) { this->Id = In_Id; };

    UFUNCTION(BlueprintCallable)
    bool IdIsSet() const {return this->Id.IsSet();};

    TOptional<FString> Username;

    UFUNCTION(BlueprintCallable)
    const FString GetUsername() const { return this->Username.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetUsername(FString In_Username) { this->Username = In_Username; };

    UFUNCTION(BlueprintCallable)
    bool UsernameIsSet() const {return this->Username.IsSet();};

    TOptional<FString> FirstName;

    UFUNCTION(BlueprintCallable)
    const FString GetFirstName() const { return this->FirstName.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetFirstName(FString In_FirstName) { this->FirstName = In_FirstName; };

    UFUNCTION(BlueprintCallable)
    bool FirstNameIsSet() const {return this->FirstName.IsSet();};

    TOptional<FString> LastName;

    UFUNCTION(BlueprintCallable)
    const FString GetLastName() const { return this->LastName.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetLastName(FString In_LastName) { this->LastName = In_LastName; };

    UFUNCTION(BlueprintCallable)
    bool LastNameIsSet() const {return this->LastName.IsSet();};

    TOptional<FString> Email;

    UFUNCTION(BlueprintCallable)
    const FString GetEmail() const { return this->Email.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetEmail(FString In_Email) { this->Email = In_Email; };

    UFUNCTION(BlueprintCallable)
    bool EmailIsSet() const {return this->Email.IsSet();};

    TOptional<FString> Password;

    UFUNCTION(BlueprintCallable)
    const FString GetPassword() const { return this->Password.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetPassword(FString In_Password) { this->Password = In_Password; };

    UFUNCTION(BlueprintCallable)
    bool PasswordIsSet() const {return this->Password.IsSet();};

    TOptional<FString> Phone;

    UFUNCTION(BlueprintCallable)
    const FString GetPhone() const { return this->Phone.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetPhone(FString In_Phone) { this->Phone = In_Phone; };

    UFUNCTION(BlueprintCallable)
    bool PhoneIsSet() const {return this->Phone.IsSet();};

    /* User Status */
    TOptional<int32> UserStatus;

    UFUNCTION(BlueprintCallable)
    const int32 GetUserStatus() const { return this->UserStatus.GetValue(); };

    UFUNCTION(BlueprintCallable)
    void SetUserStatus(int32 In_UserStatus) { this->UserStatus = In_UserStatus; };

    UFUNCTION(BlueprintCallable)
    bool UserStatusIsSet() const {return this->UserStatus.IsSet();};

private:

};



namespace openapi
{

    FString ToString(const UOAPIUser& In_User);
    void WriteJsonValue(JsonWriter& Writer, UOAPIUser* Value);

}
